name: CI

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Run Linter
        run: make code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Run Tests and Generate Coverage
        run: make test/coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
